name: 💡 Feature Request
description: Suggest a new idea or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the details below.

  - type: input
    id: title
    attributes:
      label: Feature title
      placeholder: Short summary of the feature

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you’ve considered?

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or references.
